# Generated by Django 3.2 on 2023-03-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'default_related_name': 'reviews', 'ordering': ['-pub_date']},
        ),
    ]
