# Generated by Django 3.2 on 2023-03-22 17:07

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230322_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='введите год выпуска', validators=[reviews.models.validate_year], verbose_name='год выпуска'),
        ),
    ]
